#server:
#  port: 8080
#  session-timeout: 30
#  tomcat.max-threads: 0
#  tomcat.uri-encoding: UTF-8

#redis配置
#redis:
#  host: 192.168.9.253
#  port: 6379
#  password: Redis_00_hiot
#  # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
#  database: 0
#  # 连接超时时间（毫秒）
#  timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
#  # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
#  lettuce:
#    pool:
#      # 连接池中的最大空闲连接 默认 8
#      max-idle: 500
#      # 连接池中的最小空闲连接 默认 0
#      min-idle: 50
#      # 等待可用连接的最大时间，负数为不限制
#      max-wait:  60s
#      # 连接池最大连接数（使用负值表示没有限制 -1） 默认 8
#      max-active: -1

#datasource:
#  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  url: jdbc:sqlserver://localhost:1433;DatabaseName=test001
#  username: sa
#  password: Hu12345!
#  type: com.alibaba.druid.pool.DruidDataSource
#  druid:
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
#    initial-size: 5
#    min-idle: 5
#    max-active: 20
#    # 配置获取连接等待超时的时间
#    max-wait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    time-between-eviction-runs-millis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    min-evictable-idle-time-millis: 300000
#    #每个数据库都不一样的 注意要 #SELECT 1 FROM DUAL
#    validation-query: SELECT 1
#    test-while-idle: true  # 当连接空闲时，是否执行连接测试
#    test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
#    test-on-return: false  # 在连接归还到连接池时是否测试该连接
#
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    pool-prepared-statements: true
#    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    max-pool-prepared-statement-per-connection-size: 20
#    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: config,wall,stat
#    use-global-data-source-stat: true
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    #慢SQL记录 如果上面validationQuery: SELECT 1 没有配置，而你配置了就会报错null
#    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#
#    # 配置监控服务器
#    stat-view-servlet:
#      login-username: admin
#      login-password: 123456
#      reset-enable: false
#      url-pattern: /druid/*
#      # 添加IP白名单
#      #allow:
#      # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
#      #deny:
#    web-stat-filter:
#      # 添加过滤规则
#      url-pattern: /*
#      # 忽略过滤格式
#      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"